version: '3.8'

services:
  settings_db:
    image: postgres:15
    container_name: settings_db
    environment:
      POSTGRES_USER: ${SETTINGS_DB_USER}
      POSTGRES_PASSWORD: ${SETTINGS_DB_PASSWORD}
      POSTGRES_DB: ${SETTINGS_DB_NAME}
    ports:
      - "${SETTINGS_DB_PORT}:${SETTINGS_DB_PORT}"
    volumes:
      - settings_db_data:/var/lib/postgresql/data
    networks:
      - app_network

  orders_db:
    image: postgres:15
    container_name: orders_db
    environment:
      POSTGRES_USER: ${ORDER_DB_USER}
      POSTGRES_PASSWORD: ${ORDER_DB_PASSWORD}
      POSTGRES_DB: ${ORDER_DB_NAME}
    ports:
      - "5433:${ORDER_DB_PORT}"
    volumes:
      - orders_db_data:/var/lib/postgresql/data
    networks:
      - app_network

  settings_service:
    build:
      context: .
      dockerfile: ./apps/settings/dockerfile
    container_name: settings_service
    ports:
      - ${SETTINGS_PORT}:${SETTINGS_PORT}
    environment:
      SETTINGS_DATABASE_URL: ${SETTINGS_DATABASE_URL}
      SETTINGS_DB_USER: ${SETTINGS_DB_USER}
      SETTINGS_DB_PASSWORD: ${SETTINGS_DB_PASSWORD}
      SETTINGS_DB_NAME: ${SETTINGS_DB_NAME}
      SETTINGS_DB_PORT: ${SETTINGS_DB_PORT}
      SETTINGS_DB_EMAIL: ${SETTINGS_DB_EMAIL}
    depends_on:
      - settings_db
    networks:
      - app_network

  orders_service:
    build:
      context: .
      dockerfile: ./apps/orders/dockerfile
    container_name: orders_service
    ports:
      - ${ORDER_PORT}:${ORDER_PORT}
    environment:
      ORDER_DATABASE_URL: ${ORDER_DATABASE_URL}
      ORDER_DB_USER: ${ORDER_DB_USER}
      ORDER_DB_PASSWORD: ${ORDER_DB_PASSWORD}
      ORDER_DB_NAME: ${ORDER_DB_NAME}
      ORDER_DB_PORT: ${ORDER_DB_PORT}
      ORDERS_DB_EMAIL: ${ORDERS_DB_EMAIL}
    depends_on:
      - orders_db
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  settings_db_data:
  orders_db_data: